version: '3'

services:
  tarantool1:
    container_name: dg.tarantool
    image: tarantool/tarantool:latest
    ports:
      - "3302:3301"
    volumes:
      - ./tarantool.start:/opt/tarantool
      - ./tarantool.cache:/var/lib/tarantool
    command: tarantool /opt/tarantool/script.lua

  pdg:
    build:
      context: .
      dockerfile: Dockerfile.pdg
    image: pdg
    container_name: pdg
    environment:
      - CLICKHOUSE_URL=http://10.2.22.54:8123
      - CLICKHOUSE_DB=pieflow
      - TARANTOOL_PORT=3302
      - GATHERING_TIME_OFFSET=1800  # 60 * 30 * 1 == 30 minutes
      - UPDATING_INTERVAL=1800      # 60 * 30 * 1 == 30 minutes
      - FACT_EXPIRATION_TIME=10800  # 60 * 60 * 3 == 3 hours
    network_mode: host
    depends_on:
      - tarantool1

  cl:
    build:
      context: .
      dockerfile: Dockerfile.cl
    image: cl
    container_name: cl
    environment:
      - CLICKHOUSE_URL=http://10.2.22.54:8123
      - CLICKHOUSE_DB=pieflow
      - TARANTOOL_PORT=3302
      - GATHERING_TIME_OFFSET=900   # 60 * 15 * 1 == 15 minutes
      - UPDATING_INTERVAL=1800      # 60 * 30 * 1 == 30 minutes
      - FACT_EXPIRATION_TIME=10800  # 60 * 60 * 3 == 3 hours
    network_mode: host
      depends_on:
        - tarantool1